# Generated by Django 5.0.2 on 2024-07-29 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_reset_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
