# Generated by Django 4.2.3 on 2024-02-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_category_product_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'technology'), ('home', 'home'), ('fashion', 'fashion'), ('accessories', 'accessories'), ('electronics', 'electronics')], max_length=100, null=True),
        ),
    ]
