# Generated by Django 4.2.3 on 2024-02-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('technology', 'technology'), ('home', 'home'), ('fashion', 'fashion'), ('accessories', 'accessories'), ('electronics', 'electronics')], max_length=100),
        ),
    ]
