# Generated by Django 5.0.2 on 2024-07-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_id_alter_review_id'),
    ]

    operations = [
    ]
