# Generated by Django 4.2.3 on 2024-02-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_code',
        ),
    ]
