# Generated by Django 4.2.3 on 2024-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paystatue',
            field=models.CharField(choices=[('paid', 'paid'), ('not paid', 'not paid')], default='not paid', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payway',
            field=models.CharField(choices=[('cod', 'cod'), ('card', 'card')], default='cod', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='statue',
            field=models.CharField(choices=[('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='processing', max_length=100),
        ),
    ]
