# Generated by Django 4.2.3 on 2024-02-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_paystatue_alter_order_payway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
