# Generated by Django 4.2.3 on 2024-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cartitem_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
